DROP TABLE IF EXISTS "Invoice";
DROP TABLE IF EXISTS "BillingAccount";
ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_tenantId_fkey";
ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_packageTemplateId_fkey";
DROP INDEX IF EXISTS "User_tenantId_idx";
DROP INDEX IF EXISTS "User_packageTemplateId_idx";
ALTER TABLE "User" DROP COLUMN IF EXISTS "tenantId";
ALTER TABLE "User" DROP COLUMN IF EXISTS "packageTemplateId";
DROP TABLE IF EXISTS "Tenant";
DROP TABLE IF EXISTS "PackageTemplate";
DROP TYPE IF EXISTS "TenantStatus";
DROP TYPE IF EXISTS "PackageTemplateStatus";
DROP TYPE IF EXISTS "BillingAccountStatus";
DROP TYPE IF EXISTS "InvoiceStatus";
