ALTER TABLE "ApiRequest" DROP CONSTRAINT IF EXISTS "ApiRequest_dedicatedRouteRuleId_fkey";
ALTER TABLE "DedicatedRouteRule" DROP CONSTRAINT IF EXISTS "DedicatedRouteRule_userId_fkey";
ALTER TABLE "DedicatedRouteRule" DROP CONSTRAINT IF EXISTS "DedicatedRouteRule_apiKeyId_fkey";
ALTER TABLE "DedicatedRouteRule" DROP CONSTRAINT IF EXISTS "DedicatedRouteRule_accessTierId_fkey";
ALTER TABLE "DedicatedRouteRule" DROP CONSTRAINT IF EXISTS "DedicatedRouteRule_upstreamProviderKeyId_fkey";
DROP INDEX IF EXISTS "ApiRequest_dedicatedRouteRuleId_createdAt_idx";
ALTER TABLE "ApiRequest" DROP COLUMN IF EXISTS "dedicatedRouteRuleId";
ALTER TABLE "IpAccessTierRule" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "IpAccessTierRule" ALTER COLUMN "status" TYPE "AccessTierStatus" USING "status"::text::"AccessTierStatus";
ALTER TABLE "IpAccessTierRule" ALTER COLUMN "status" SET DEFAULT 'ACTIVE';
DROP TABLE IF EXISTS "DedicatedRouteRule";
DROP TYPE IF EXISTS "DedicatedRouteTargetType";
DROP TYPE IF EXISTS "DedicatedRouteRuleStatus";
